function [preprocessGroundTruthNavOrientationEulerAngleDeg] = getPreprocessGroundTruthNavOrientationEulerAngleDeg(preprocessRawFlatData)
%UNTITLED2 此处提供此函数的摘要
%   此处提供详细说明
PreprocessGroundTruthNavOrientationRotationMatrix = getPreprocessGroundTruthNavOrientationRotationMatrix(preprocessRawFlatData);
[PreprocessGroundTruthNavOrientationEulerAnglePitch,PreprocessGroundTruthNavOrientationEulerAngleRoll,PreprocessGroundTruthNavOrientationEulerAngleYaw] = dcm2angle(PreprocessGroundTruthNavOrientationRotationMatrix,'XYZ');
preprocessGroundTruthNavOrientationEulerAngleDeg = rad2deg(horzcat(PreprocessGroundTruthNavOrientationEulerAnglePitch,PreprocessGroundTruthNavOrientationEulerAngleRoll,PreprocessGroundTruthNavOrientationEulerAngleYaw));

end