function [preprocessGroundTruthNavSE] = loadPreprocessGroundTruthNavSE(folderPath)
%UNTITLED2 此处提供此函数的摘要
%   此处提供详细说明

preprocessRawFlatData = loadPreprocessRawFlat(folderPath);

preprocessGroundTruthNavOrientation = getPreprocessGroundTruthNavOrientationRotationMatrix(preprocessRawFlatData);
preprocessGroundTruthNavPosition = getPreprocessGroundTruthNavPosition(preprocessRawFlatData);
preprocessGroundTruthNavSEObject = se3(preprocessGroundTruthNavOrientation,preprocessGroundTruthNavPosition);

preprocessGroundTruthNavSE = tform(preprocessGroundTruthNavSEObject);

end