function oxtsRawInterpGeodeticCoordinate = loadOxtsRawInterpGeodeticCoordinate(extractFolderPath)

cOxtsFolderName = 'oxts';
cOxtsRawDataInterpGeodeticCoordinateMatFileName = 'OxtsRawDataInterpGeodeticCoordinate.mat';

cOxtsRowDataInterpGeodeticCoordinateMatFilePath = fullfile(extractFolderPath,cOxtsFolderName,cOxtsRawDataInterpGeodeticCoordinateMatFileName);
if isfile(cOxtsRowDataInterpGeodeticCoordinateMatFilePath)
    oxtsRawInterpGeodeticCoordinate = load(cOxtsRowDataInterpGeodeticCoordinateMatFilePath,'-mat').oxtsRawInterpGeodeticCoordinate;
    return;
end

oxtsRawData = loadOxtsRawData(extractFolderPath);
tOxtsRawDataTime = oxtsRawData(:,1);
tOxtsRawDataGeodeticCoordinate = oxtsRawData(:,2:4);

tReferencepheroid = wgs84Ellipsoid;
tReferenceGeodeticCoordinate = tOxtsRawDataGeodeticCoordinate(1,:);
[tOxtsRawDataENUCoordinateEast,tOxtsRawDataENUCoordinateyNorth,tOxtsRawDataENUCoordinateUp] = geodetic2enu( ...
    tOxtsRawDataGeodeticCoordinate(:,1), ...
    tOxtsRawDataGeodeticCoordinate(:,2), ...
    tOxtsRawDataGeodeticCoordinate(:,3), ...
    tReferenceGeodeticCoordinate(1), ...
    tReferenceGeodeticCoordinate(2), ...
    tReferenceGeodeticCoordinate(3), ...
    tReferencepheroid ...
);
tOxtsRawDataENUCoordinate = [tOxtsRawDataENUCoordinateEast,tOxtsRawDataENUCoordinateyNorth,tOxtsRawDataENUCoordinateUp];

tTimeHead = ceil(tOxtsRawDataTime(1));
tTimeTail = floor(tOxtsRawDataTime(end));
tInterpTime = (tTimeHead:0.01:tTimeTail)';

[~,ia,~] = unique(tOxtsRawDataTime);
resampledENUCoordinate = interp1(tOxtsRawDataTime(ia),tOxtsRawDataENUCoordinate(ia,:),tInterpTime);

[tResampledGeodeticCoordinateLat,tResampledGeodeticCoordinateLon,tResampledGeodeticCoordinateH] = enu2geodetic( ...
    resampledENUCoordinate(:,1), ...
    resampledENUCoordinate(:,2), ...
    resampledENUCoordinate(:,3), ...
    tReferenceGeodeticCoordinate(1), ...
    tReferenceGeodeticCoordinate(2), ...
    tReferenceGeodeticCoordinate(3), ...
    tReferencepheroid ...
);

oxtsRawInterpGeodeticCoordinate = [tInterpTime,tResampledGeodeticCoordinateLat,tResampledGeodeticCoordinateLon,tResampledGeodeticCoordinateH];

save(cOxtsRowDataInterpGeodeticCoordinateMatFilePath,'oxtsRawInterpGeodeticCoordinate');
